//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SugarSystem.Client.UpdateSignaturePath {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UpdateKN9StatusSoap", Namespace="http://tempuri.org/")]
    public partial class UpdateKN9Status : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SignatureKN9OperationCompleted;
        
        private System.Threading.SendOrPostCallback SignatureKN10OperationCompleted;
        
        private System.Threading.SendOrPostCallback SignatureA1OperationCompleted;
        
        private System.Threading.SendOrPostCallback SignatureA2OperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadSignedPDFContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadSignedPDFLicenseOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadSignedPDF_CancelRenewOperationCompleted;
        
        private System.Threading.SendOrPostCallback SHOWALLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GETBYKN9OperationCompleted;
        
        private System.Threading.SendOrPostCallback DELETEByAutoNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateKN9AfterStampKN10OperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateKN9AfterStampKN9OperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateA2PrintStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UpdateKN9Status() {
            this.Url = global::SugarSystem.Client.Properties.Settings.Default.Client_UpdateSignaturePath_UpdateKN9Status;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SignatureKN9CompletedEventHandler SignatureKN9Completed;
        
        /// <remarks/>
        public event SignatureKN10CompletedEventHandler SignatureKN10Completed;
        
        /// <remarks/>
        public event SignatureA1CompletedEventHandler SignatureA1Completed;
        
        /// <remarks/>
        public event SignatureA2CompletedEventHandler SignatureA2Completed;
        
        /// <remarks/>
        public event UploadSignedPDFContractCompletedEventHandler UploadSignedPDFContractCompleted;
        
        /// <remarks/>
        public event UploadSignedPDFLicenseCompletedEventHandler UploadSignedPDFLicenseCompleted;
        
        /// <remarks/>
        public event UploadSignedPDF_CancelRenewCompletedEventHandler UploadSignedPDF_CancelRenewCompleted;
        
        /// <remarks/>
        public event SHOWALLCompletedEventHandler SHOWALLCompleted;
        
        /// <remarks/>
        public event GETBYKN9CompletedEventHandler GETBYKN9Completed;
        
        /// <remarks/>
        public event DELETEByAutoNumberCompletedEventHandler DELETEByAutoNumberCompleted;
        
        /// <remarks/>
        public event UpdateKN9AfterStampKN10CompletedEventHandler UpdateKN9AfterStampKN10Completed;
        
        /// <remarks/>
        public event UpdateKN9AfterStampKN9CompletedEventHandler UpdateKN9AfterStampKN9Completed;
        
        /// <remarks/>
        public event UpdateA2PrintStatusCompletedEventHandler UpdateA2PrintStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SignatureKN9", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SignatureKN9(string _RefNo, string _SignaturePath) {
            object[] results = this.Invoke("SignatureKN9", new object[] {
                        _RefNo,
                        _SignaturePath});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SignatureKN9Async(string _RefNo, string _SignaturePath) {
            this.SignatureKN9Async(_RefNo, _SignaturePath, null);
        }
        
        /// <remarks/>
        public void SignatureKN9Async(string _RefNo, string _SignaturePath, object userState) {
            if ((this.SignatureKN9OperationCompleted == null)) {
                this.SignatureKN9OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignatureKN9OperationCompleted);
            }
            this.InvokeAsync("SignatureKN9", new object[] {
                        _RefNo,
                        _SignaturePath}, this.SignatureKN9OperationCompleted, userState);
        }
        
        private void OnSignatureKN9OperationCompleted(object arg) {
            if ((this.SignatureKN9Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignatureKN9Completed(this, new SignatureKN9CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SignatureKN10", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SignatureKN10(string _RefNo, string _SignaturePath) {
            object[] results = this.Invoke("SignatureKN10", new object[] {
                        _RefNo,
                        _SignaturePath});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SignatureKN10Async(string _RefNo, string _SignaturePath) {
            this.SignatureKN10Async(_RefNo, _SignaturePath, null);
        }
        
        /// <remarks/>
        public void SignatureKN10Async(string _RefNo, string _SignaturePath, object userState) {
            if ((this.SignatureKN10OperationCompleted == null)) {
                this.SignatureKN10OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignatureKN10OperationCompleted);
            }
            this.InvokeAsync("SignatureKN10", new object[] {
                        _RefNo,
                        _SignaturePath}, this.SignatureKN10OperationCompleted, userState);
        }
        
        private void OnSignatureKN10OperationCompleted(object arg) {
            if ((this.SignatureKN10Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignatureKN10Completed(this, new SignatureKN10CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SignatureA1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SignatureA1(string _RefNo, string _SignaturePath) {
            object[] results = this.Invoke("SignatureA1", new object[] {
                        _RefNo,
                        _SignaturePath});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SignatureA1Async(string _RefNo, string _SignaturePath) {
            this.SignatureA1Async(_RefNo, _SignaturePath, null);
        }
        
        /// <remarks/>
        public void SignatureA1Async(string _RefNo, string _SignaturePath, object userState) {
            if ((this.SignatureA1OperationCompleted == null)) {
                this.SignatureA1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignatureA1OperationCompleted);
            }
            this.InvokeAsync("SignatureA1", new object[] {
                        _RefNo,
                        _SignaturePath}, this.SignatureA1OperationCompleted, userState);
        }
        
        private void OnSignatureA1OperationCompleted(object arg) {
            if ((this.SignatureA1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignatureA1Completed(this, new SignatureA1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SignatureA2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SignatureA2(string _RefNo, string _SignaturePath) {
            object[] results = this.Invoke("SignatureA2", new object[] {
                        _RefNo,
                        _SignaturePath});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SignatureA2Async(string _RefNo, string _SignaturePath) {
            this.SignatureA2Async(_RefNo, _SignaturePath, null);
        }
        
        /// <remarks/>
        public void SignatureA2Async(string _RefNo, string _SignaturePath, object userState) {
            if ((this.SignatureA2OperationCompleted == null)) {
                this.SignatureA2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignatureA2OperationCompleted);
            }
            this.InvokeAsync("SignatureA2", new object[] {
                        _RefNo,
                        _SignaturePath}, this.SignatureA2OperationCompleted, userState);
        }
        
        private void OnSignatureA2OperationCompleted(object arg) {
            if ((this.SignatureA2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignatureA2Completed(this, new SignatureA2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadSignedPDFContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UploadResponeMsg UploadSignedPDFContract(string PdfFile, string CompNo, string ContractNo) {
            object[] results = this.Invoke("UploadSignedPDFContract", new object[] {
                        PdfFile,
                        CompNo,
                        ContractNo});
            return ((UploadResponeMsg)(results[0]));
        }
        
        /// <remarks/>
        public void UploadSignedPDFContractAsync(string PdfFile, string CompNo, string ContractNo) {
            this.UploadSignedPDFContractAsync(PdfFile, CompNo, ContractNo, null);
        }
        
        /// <remarks/>
        public void UploadSignedPDFContractAsync(string PdfFile, string CompNo, string ContractNo, object userState) {
            if ((this.UploadSignedPDFContractOperationCompleted == null)) {
                this.UploadSignedPDFContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadSignedPDFContractOperationCompleted);
            }
            this.InvokeAsync("UploadSignedPDFContract", new object[] {
                        PdfFile,
                        CompNo,
                        ContractNo}, this.UploadSignedPDFContractOperationCompleted, userState);
        }
        
        private void OnUploadSignedPDFContractOperationCompleted(object arg) {
            if ((this.UploadSignedPDFContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadSignedPDFContractCompleted(this, new UploadSignedPDFContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadSignedPDFLicense", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UploadResponeMsg UploadSignedPDFLicense(string PdfFile, string RefNo, string FormType) {
            object[] results = this.Invoke("UploadSignedPDFLicense", new object[] {
                        PdfFile,
                        RefNo,
                        FormType});
            return ((UploadResponeMsg)(results[0]));
        }
        
        /// <remarks/>
        public void UploadSignedPDFLicenseAsync(string PdfFile, string RefNo, string FormType) {
            this.UploadSignedPDFLicenseAsync(PdfFile, RefNo, FormType, null);
        }
        
        /// <remarks/>
        public void UploadSignedPDFLicenseAsync(string PdfFile, string RefNo, string FormType, object userState) {
            if ((this.UploadSignedPDFLicenseOperationCompleted == null)) {
                this.UploadSignedPDFLicenseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadSignedPDFLicenseOperationCompleted);
            }
            this.InvokeAsync("UploadSignedPDFLicense", new object[] {
                        PdfFile,
                        RefNo,
                        FormType}, this.UploadSignedPDFLicenseOperationCompleted, userState);
        }
        
        private void OnUploadSignedPDFLicenseOperationCompleted(object arg) {
            if ((this.UploadSignedPDFLicenseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadSignedPDFLicenseCompleted(this, new UploadSignedPDFLicenseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadSignedPDF_CancelRenew", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadSignedPDF_CancelRenew(string PdfFile, string RefNo, string FormType, string ReqNo) {
            object[] results = this.Invoke("UploadSignedPDF_CancelRenew", new object[] {
                        PdfFile,
                        RefNo,
                        FormType,
                        ReqNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadSignedPDF_CancelRenewAsync(string PdfFile, string RefNo, string FormType, string ReqNo) {
            this.UploadSignedPDF_CancelRenewAsync(PdfFile, RefNo, FormType, ReqNo, null);
        }
        
        /// <remarks/>
        public void UploadSignedPDF_CancelRenewAsync(string PdfFile, string RefNo, string FormType, string ReqNo, object userState) {
            if ((this.UploadSignedPDF_CancelRenewOperationCompleted == null)) {
                this.UploadSignedPDF_CancelRenewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadSignedPDF_CancelRenewOperationCompleted);
            }
            this.InvokeAsync("UploadSignedPDF_CancelRenew", new object[] {
                        PdfFile,
                        RefNo,
                        FormType,
                        ReqNo}, this.UploadSignedPDF_CancelRenewOperationCompleted, userState);
        }
        
        private void OnUploadSignedPDF_CancelRenewOperationCompleted(object arg) {
            if ((this.UploadSignedPDF_CancelRenewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadSignedPDF_CancelRenewCompleted(this, new UploadSignedPDF_CancelRenewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SHOWALL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SHOWALL() {
            object[] results = this.Invoke("SHOWALL", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SHOWALLAsync() {
            this.SHOWALLAsync(null);
        }
        
        /// <remarks/>
        public void SHOWALLAsync(object userState) {
            if ((this.SHOWALLOperationCompleted == null)) {
                this.SHOWALLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSHOWALLOperationCompleted);
            }
            this.InvokeAsync("SHOWALL", new object[0], this.SHOWALLOperationCompleted, userState);
        }
        
        private void OnSHOWALLOperationCompleted(object arg) {
            if ((this.SHOWALLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SHOWALLCompleted(this, new SHOWALLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GETBYKN9", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GETBYKN9(string kn9) {
            object[] results = this.Invoke("GETBYKN9", new object[] {
                        kn9});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GETBYKN9Async(string kn9) {
            this.GETBYKN9Async(kn9, null);
        }
        
        /// <remarks/>
        public void GETBYKN9Async(string kn9, object userState) {
            if ((this.GETBYKN9OperationCompleted == null)) {
                this.GETBYKN9OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGETBYKN9OperationCompleted);
            }
            this.InvokeAsync("GETBYKN9", new object[] {
                        kn9}, this.GETBYKN9OperationCompleted, userState);
        }
        
        private void OnGETBYKN9OperationCompleted(object arg) {
            if ((this.GETBYKN9Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GETBYKN9Completed(this, new GETBYKN9CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DELETEByAutoNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DELETEByAutoNumber(int AutoNumber) {
            object[] results = this.Invoke("DELETEByAutoNumber", new object[] {
                        AutoNumber});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DELETEByAutoNumberAsync(int AutoNumber) {
            this.DELETEByAutoNumberAsync(AutoNumber, null);
        }
        
        /// <remarks/>
        public void DELETEByAutoNumberAsync(int AutoNumber, object userState) {
            if ((this.DELETEByAutoNumberOperationCompleted == null)) {
                this.DELETEByAutoNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDELETEByAutoNumberOperationCompleted);
            }
            this.InvokeAsync("DELETEByAutoNumber", new object[] {
                        AutoNumber}, this.DELETEByAutoNumberOperationCompleted, userState);
        }
        
        private void OnDELETEByAutoNumberOperationCompleted(object arg) {
            if ((this.DELETEByAutoNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DELETEByAutoNumberCompleted(this, new DELETEByAutoNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateKN9AfterStampKN10", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateKN9AfterStampKN10(string kn9no, System.DateTime recdate, System.DateTime expiredate, string status, string bookno, string seqno) {
            object[] results = this.Invoke("UpdateKN9AfterStampKN10", new object[] {
                        kn9no,
                        recdate,
                        expiredate,
                        status,
                        bookno,
                        seqno});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateKN9AfterStampKN10Async(string kn9no, System.DateTime recdate, System.DateTime expiredate, string status, string bookno, string seqno) {
            this.UpdateKN9AfterStampKN10Async(kn9no, recdate, expiredate, status, bookno, seqno, null);
        }
        
        /// <remarks/>
        public void UpdateKN9AfterStampKN10Async(string kn9no, System.DateTime recdate, System.DateTime expiredate, string status, string bookno, string seqno, object userState) {
            if ((this.UpdateKN9AfterStampKN10OperationCompleted == null)) {
                this.UpdateKN9AfterStampKN10OperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateKN9AfterStampKN10OperationCompleted);
            }
            this.InvokeAsync("UpdateKN9AfterStampKN10", new object[] {
                        kn9no,
                        recdate,
                        expiredate,
                        status,
                        bookno,
                        seqno}, this.UpdateKN9AfterStampKN10OperationCompleted, userState);
        }
        
        private void OnUpdateKN9AfterStampKN10OperationCompleted(object arg) {
            if ((this.UpdateKN9AfterStampKN10Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateKN9AfterStampKN10Completed(this, new UpdateKN9AfterStampKN10CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateKN9AfterStampKN9", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateKN9AfterStampKN9(string strDate, string strKN10, string strKN9No) {
            object[] results = this.Invoke("UpdateKN9AfterStampKN9", new object[] {
                        strDate,
                        strKN10,
                        strKN9No});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateKN9AfterStampKN9Async(string strDate, string strKN10, string strKN9No) {
            this.UpdateKN9AfterStampKN9Async(strDate, strKN10, strKN9No, null);
        }
        
        /// <remarks/>
        public void UpdateKN9AfterStampKN9Async(string strDate, string strKN10, string strKN9No, object userState) {
            if ((this.UpdateKN9AfterStampKN9OperationCompleted == null)) {
                this.UpdateKN9AfterStampKN9OperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateKN9AfterStampKN9OperationCompleted);
            }
            this.InvokeAsync("UpdateKN9AfterStampKN9", new object[] {
                        strDate,
                        strKN10,
                        strKN9No}, this.UpdateKN9AfterStampKN9OperationCompleted, userState);
        }
        
        private void OnUpdateKN9AfterStampKN9OperationCompleted(object arg) {
            if ((this.UpdateKN9AfterStampKN9Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateKN9AfterStampKN9Completed(this, new UpdateKN9AfterStampKN9CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateA2PrintStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateA2PrintStatus(string kn9no) {
            object[] results = this.Invoke("UpdateA2PrintStatus", new object[] {
                        kn9no});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateA2PrintStatusAsync(string kn9no) {
            this.UpdateA2PrintStatusAsync(kn9no, null);
        }
        
        /// <remarks/>
        public void UpdateA2PrintStatusAsync(string kn9no, object userState) {
            if ((this.UpdateA2PrintStatusOperationCompleted == null)) {
                this.UpdateA2PrintStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateA2PrintStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateA2PrintStatus", new object[] {
                        kn9no}, this.UpdateA2PrintStatusOperationCompleted, userState);
        }
        
        private void OnUpdateA2PrintStatusOperationCompleted(object arg) {
            if ((this.UpdateA2PrintStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateA2PrintStatusCompleted(this, new UpdateA2PrintStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadResponeMsg {
        
        private int responseIDField;
        
        private string responseResultField;
        
        /// <remarks/>
        public int ResponseID {
            get {
                return this.responseIDField;
            }
            set {
                this.responseIDField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseResult {
            get {
                return this.responseResultField;
            }
            set {
                this.responseResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SignatureKN9CompletedEventHandler(object sender, SignatureKN9CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignatureKN9CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignatureKN9CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SignatureKN10CompletedEventHandler(object sender, SignatureKN10CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignatureKN10CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignatureKN10CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SignatureA1CompletedEventHandler(object sender, SignatureA1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignatureA1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignatureA1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SignatureA2CompletedEventHandler(object sender, SignatureA2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignatureA2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignatureA2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UploadSignedPDFContractCompletedEventHandler(object sender, UploadSignedPDFContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadSignedPDFContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadSignedPDFContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UploadResponeMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UploadResponeMsg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UploadSignedPDFLicenseCompletedEventHandler(object sender, UploadSignedPDFLicenseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadSignedPDFLicenseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadSignedPDFLicenseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UploadResponeMsg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UploadResponeMsg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UploadSignedPDF_CancelRenewCompletedEventHandler(object sender, UploadSignedPDF_CancelRenewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadSignedPDF_CancelRenewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadSignedPDF_CancelRenewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SHOWALLCompletedEventHandler(object sender, SHOWALLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SHOWALLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SHOWALLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GETBYKN9CompletedEventHandler(object sender, GETBYKN9CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GETBYKN9CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GETBYKN9CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DELETEByAutoNumberCompletedEventHandler(object sender, DELETEByAutoNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DELETEByAutoNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DELETEByAutoNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateKN9AfterStampKN10CompletedEventHandler(object sender, UpdateKN9AfterStampKN10CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateKN9AfterStampKN10CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateKN9AfterStampKN10CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateKN9AfterStampKN9CompletedEventHandler(object sender, UpdateKN9AfterStampKN9CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateKN9AfterStampKN9CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateKN9AfterStampKN9CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateA2PrintStatusCompletedEventHandler(object sender, UpdateA2PrintStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateA2PrintStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateA2PrintStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591