//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SugarSystem.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string signatureField {
            get {
                return ((string)(this["signatureField"]));
            }
            set {
                this["signatureField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string signatureField2 {
            get {
                return ((string)(this["signatureField2"]));
            }
            set {
                this["signatureField2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Userts {
            get {
                return ((string)(this["Userts"]));
            }
            set {
                this["Userts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Passts {
            get {
                return ((string)(this["Passts"]));
            }
            set {
                this["Passts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Reason {
            get {
                return ((string)(this["Reason"]));
            }
            set {
                this["Reason"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Location {
            get {
                return ((string)(this["Location"]));
            }
            set {
                this["Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.840.1.101.3.4.2.1")]
        public string HASH_FUNCTION_OID {
            get {
                return ((string)(this["HASH_FUNCTION_OID"]));
            }
            set {
                this["HASH_FUNCTION_OID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string UserwsPortal {
            get {
                return ((string)(this["UserwsPortal"]));
            }
            set {
                this["UserwsPortal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string PasswsPortal {
            get {
                return ((string)(this["PasswsPortal"]));
            }
            set {
                this["PasswsPortal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FTPuser {
            get {
                return ((string)(this["FTPuser"]));
            }
            set {
                this["FTPuser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FTPpassword {
            get {
                return ((string)(this["FTPpassword"]));
            }
            set {
                this["FTPpassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string certRef {
            get {
                return ((string)(this["certRef"]));
            }
            set {
                this["certRef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string passwordedit {
            get {
                return ((string)(this["passwordedit"]));
            }
            set {
                this["passwordedit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FTPUpload {
            get {
                return ((string)(this["FTPUpload"]));
            }
            set {
                this["FTPUpload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pathWS {
            get {
                return ((string)(this["pathWS"]));
            }
            set {
                this["pathWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mock.tonproject.com/services/ocsb.asmx")]
        public string Client_wsPortal_OCSB {
            get {
                return ((string)(this["Client_wsPortal_OCSB"]));
            }
            set {
                this["Client_wsPortal_OCSB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://test.export.ocsb.go.th/WebService/UpdateKN9Status.asmx")]
        public string Client_UpdateSignaturePath_UpdateKN9Status {
            get {
                return ((string)(this["Client_UpdateSignaturePath_UpdateKN9Status"]));
            }
            set {
                this["Client_UpdateSignaturePath_UpdateKN9Status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nti_wsUser")]
        public string Userpdf {
            get {
                return ((string)(this["Userpdf"]));
            }
            set {
                this["Userpdf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("azeDAGYJ")]
        public string Passpdf {
            get {
                return ((string)(this["Passpdf"]));
            }
            set {
                this["Passpdf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test.time.teda.th")]
        public string URLts {
            get {
                return ((string)(this["URLts"]));
            }
            set {
                this["URLts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.764.1.4.100.3.1000.1.1.1.1")]
        public string OIDKN9 {
            get {
                return ((string)(this["OIDKN9"]));
            }
            set {
                this["OIDKN9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test.certificate.teda.th/service")]
        public string URLcergenserver {
            get {
                return ((string)(this["URLcergenserver"]));
            }
            set {
                this["URLcergenserver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://test.export.ocsb.go.th")]
        public string URLwebsite {
            get {
                return ((string)(this["URLwebsite"]));
            }
            set {
                this["URLwebsite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://test.export.ocsb.go.th/validation/license.aspx")]
        public string ValidationURL {
            get {
                return ((string)(this["ValidationURL"]));
            }
            set {
                this["ValidationURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SHA1")]
        public string HASH_FUNCTION {
            get {
                return ((string)(this["HASH_FUNCTION"]));
            }
            set {
                this["HASH_FUNCTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.764.1.4.100.3.1000.1.2.1.1")]
        public string OIDKN10 {
            get {
                return ((string)(this["OIDKN10"]));
            }
            set {
                this["OIDKN10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.764.1.4.100.3.1000.1.4.1.1")]
        public string OIDA1 {
            get {
                return ((string)(this["OIDA1"]));
            }
            set {
                this["OIDA1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.764.1.4.100.3.1000.1.5.1.1")]
        public string OIDA2 {
            get {
                return ((string)(this["OIDA2"]));
            }
            set {
                this["OIDA2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.764.1.4.100.3.1000.1.3.1.1")]
        public string OidCRKN {
            get {
                return ((string)(this["OidCRKN"]));
            }
            set {
                this["OidCRKN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.764.1.4.100.3.1000.1.7.1.1")]
        public string OidCNA2 {
            get {
                return ((string)(this["OidCNA2"]));
            }
            set {
                this["OidCNA2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.764.1.4.100.3.1000.1.6.1.1")]
        public string OidRNA2 {
            get {
                return ((string)(this["OidRNA2"]));
            }
            set {
                this["OidRNA2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://test.exportapi.ocsb.go.th")]
        public string URL_API {
            get {
                return ((string)(this["URL_API"]));
            }
            set {
                this["URL_API"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PDF4NET50-15N7J-PUNAE-FGK2F-JELKS-R2SJ1")]
        public string SerialPDF4NET {
            get {
                return ((string)(this["SerialPDF4NET"]));
            }
            set {
                this["SerialPDF4NET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.764.1.4.100.3.1000.1.1.1.2")]
        public string OIDKN9_Scm {
            get {
                return ((string)(this["OIDKN9_Scm"]));
            }
            set {
                this["OIDKN9_Scm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.764.1.4.100.3.1000.1.2.1.2")]
        public string OIDKN10_Scm {
            get {
                return ((string)(this["OIDKN10_Scm"]));
            }
            set {
                this["OIDKN10_Scm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.764.1.4.100.3.1000.1.3.1.2")]
        public string OidCRKN_Scm {
            get {
                return ((string)(this["OidCRKN_Scm"]));
            }
            set {
                this["OidCRKN_Scm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.764.1.4.100.3.1000.1.4.1.2")]
        public string OIDA1_Scm {
            get {
                return ((string)(this["OIDA1_Scm"]));
            }
            set {
                this["OIDA1_Scm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.764.1.4.100.3.1000.1.5.1.2")]
        public string OIDA2_Scm {
            get {
                return ((string)(this["OIDA2_Scm"]));
            }
            set {
                this["OIDA2_Scm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.764.1.4.100.3.1000.1.7.1.2")]
        public string OidCNA2_Scm {
            get {
                return ((string)(this["OidCNA2_Scm"]));
            }
            set {
                this["OidCNA2_Scm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.16.764.1.4.100.3.1000.1.6.1.2")]
        public string OidRNA2_Scm {
            get {
                return ((string)(this["OidRNA2_Scm"]));
            }
            set {
                this["OidRNA2_Scm"] = value;
            }
        }
    }
}
