//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertificateGenerationSampleCode.CertificateGenerationWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://certificate.teda.th/service", ConfigurationName="CertificateGenerationWS.CertificateGenerationService")]
    public interface CertificateGenerationService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://certificate.teda.th/service/CertificateGenerationService/generationReqeust" +
            "Request", ReplyAction="http://certificate.teda.th/service/CertificateGenerationService/generationReqeust" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(certificateGenerationResponseObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(generationReqeustResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(generationReqeust))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(response))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CertificateGenerationSampleCode.CertificateGenerationWS.generationReqeustResponse1 generationReqeust(CertificateGenerationSampleCode.CertificateGenerationWS.generationReqeustRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificate.teda.th/service")]
    public partial class certificateGenerationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string certificateReferenceNumberField;
        
        private string formOIDField;
        
        private string hashValueField;
        
        private string hashAlgorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string certificateReferenceNumber {
            get {
                return this.certificateReferenceNumberField;
            }
            set {
                this.certificateReferenceNumberField = value;
                this.RaisePropertyChanged("certificateReferenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string formOID {
            get {
                return this.formOIDField;
            }
            set {
                this.formOIDField = value;
                this.RaisePropertyChanged("formOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string hashValue {
            get {
                return this.hashValueField;
            }
            set {
                this.hashValueField = value;
                this.RaisePropertyChanged("hashValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string hashAlgorithm {
            get {
                return this.hashAlgorithmField;
            }
            set {
                this.hashAlgorithmField = value;
                this.RaisePropertyChanged("hashAlgorithm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificate.teda.th/service")]
    public partial class certificateGenerationResponseObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serialNumberField;
        
        private string certificateReferenceNumberField;
        
        private string certificateIssueDateField;
        
        private string certificateFormField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string serialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("serialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string certificateReferenceNumber {
            get {
                return this.certificateReferenceNumberField;
            }
            set {
                this.certificateReferenceNumberField = value;
                this.RaisePropertyChanged("certificateReferenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string certificateIssueDate {
            get {
                return this.certificateIssueDateField;
            }
            set {
                this.certificateIssueDateField = value;
                this.RaisePropertyChanged("certificateIssueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string certificateForm {
            get {
                return this.certificateFormField;
            }
            set {
                this.certificateFormField = value;
                this.RaisePropertyChanged("certificateForm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificate.teda.th/service")]
    public partial class generationReqeustResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private certificateGenerationResponse returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public certificateGenerationResponse @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificate.teda.th/service")]
    public partial class certificateGenerationResponse : response {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(certificateGenerationResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificate.teda.th/service")]
    public abstract partial class response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusCodeField;
        
        private string statusMessageField;
        
        private string serviceTypeField;
        
        private string requestTimeField;
        
        private string responseTimeField;
        
        private object responseDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string statusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("statusMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string serviceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("serviceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string requestTime {
            get {
                return this.requestTimeField;
            }
            set {
                this.requestTimeField = value;
                this.RaisePropertyChanged("requestTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string responseTime {
            get {
                return this.responseTimeField;
            }
            set {
                this.responseTimeField = value;
                this.RaisePropertyChanged("responseTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public object responseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
                this.RaisePropertyChanged("responseData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://certificate.teda.th/service")]
    public partial class generationReqeust : object, System.ComponentModel.INotifyPropertyChanged {
        
        private certificateGenerationRequest certificateGenerationRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public certificateGenerationRequest certificateGenerationRequest {
            get {
                return this.certificateGenerationRequestField;
            }
            set {
                this.certificateGenerationRequestField = value;
                this.RaisePropertyChanged("certificateGenerationRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generationReqeust", WrapperNamespace="http://certificate.teda.th/service", IsWrapped=true)]
    public partial class generationReqeustRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://certificate.teda.th/service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CertificateGenerationSampleCode.CertificateGenerationWS.certificateGenerationRequest certificateGenerationRequest;
        
        public generationReqeustRequest() {
        }
        
        public generationReqeustRequest(CertificateGenerationSampleCode.CertificateGenerationWS.certificateGenerationRequest certificateGenerationRequest) {
            this.certificateGenerationRequest = certificateGenerationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generationReqeustResponse", WrapperNamespace="http://certificate.teda.th/service", IsWrapped=true)]
    public partial class generationReqeustResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://certificate.teda.th/service", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CertificateGenerationSampleCode.CertificateGenerationWS.certificateGenerationResponse @return;
        
        public generationReqeustResponse1() {
        }
        
        public generationReqeustResponse1(CertificateGenerationSampleCode.CertificateGenerationWS.certificateGenerationResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CertificateGenerationServiceChannel : CertificateGenerationSampleCode.CertificateGenerationWS.CertificateGenerationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CertificateGenerationServiceClient : System.ServiceModel.ClientBase<CertificateGenerationSampleCode.CertificateGenerationWS.CertificateGenerationService>, CertificateGenerationSampleCode.CertificateGenerationWS.CertificateGenerationService {
        
        public CertificateGenerationServiceClient() {
        }
        
        public CertificateGenerationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CertificateGenerationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificateGenerationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificateGenerationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CertificateGenerationSampleCode.CertificateGenerationWS.generationReqeustResponse1 CertificateGenerationSampleCode.CertificateGenerationWS.CertificateGenerationService.generationReqeust(CertificateGenerationSampleCode.CertificateGenerationWS.generationReqeustRequest request) {
            return base.Channel.generationReqeust(request);
        }
        
        public CertificateGenerationSampleCode.CertificateGenerationWS.certificateGenerationResponse generationReqeust(CertificateGenerationSampleCode.CertificateGenerationWS.certificateGenerationRequest certificateGenerationRequest) {
            CertificateGenerationSampleCode.CertificateGenerationWS.generationReqeustRequest inValue = new CertificateGenerationSampleCode.CertificateGenerationWS.generationReqeustRequest();
            inValue.certificateGenerationRequest = certificateGenerationRequest;
            CertificateGenerationSampleCode.CertificateGenerationWS.generationReqeustResponse1 retVal = ((CertificateGenerationSampleCode.CertificateGenerationWS.CertificateGenerationService)(this)).generationReqeust(inValue);
            return retVal.@return;
        }
    }
}
